### ISSUE TITLE
mopa:bootstrap:install:font error when composer not local

### ISSUE THREAD

**Issue by Xigi** [phiamo/MopaComposerBridge#11]
I am using the homebrew version of composer and app/console mopa:bootstrap:install:font breaks with an error:

[PharException]

internal corruption of phar "/usr/local/Cellar/composer/1.0.0-alpha9/libexec/composer" (__HALT_COMPILER(); not found)

Installing composer into the repo root is a good workaround for now.

Running the command with -v shows this:

Exception trace:
 () at /Users/Tamas/Sites/gbm/vendor/mopa/composer-bridge/src/Mopa/Bridge/Composer/Adapter/ComposerAdapter.php:77
 Phar::loadPhar() at /Users/Tamas/Sites/gbm/vendor/mopa/composer-bridge/src/Mopa/Bridge/Composer/Adapter/ComposerAdapter.php:77
 Mopa\Bridge\Composer\Adapter\ComposerAdapter::checkComposer() at /Users/Tamas/Sites/gbm/vendor/mopa/composer-bridge/src/Mopa/Bridge/Composer/Adapter/ComposerAdapter.php:105
 Mopa\Bridge\Composer\Adapter\ComposerAdapter::getComposer() at /Users/Tamas/Sites/gbm/vendor/mopa/bootstrap-bundle/Mopa/Bundle/BootstrapBundle/Command/InstallFontCommand.php:65
 Mopa\Bundle\BootstrapBundle\Command\InstallFontCommand->execute() at /Users/Tamas/Sites/gbm/vendor/symfony/symfony/src/Symfony/Component/Console/Command/Command.php:252
 Symfony\Component\Console\Command\Command->run() at /Users/Tamas/Sites/gbm/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:882
 Symfony\Component\Console\Application->doRunCommand() at /Users/Tamas/Sites/gbm/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:195
 Symfony\Component\Console\Application->doRun() at /Users/Tamas/Sites/gbm/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Console/Application.php:96
 Symfony\Bundle\FrameworkBundle\Console\Application->doRun() at /Users/Tamas/Sites/gbm/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:126
 Symfony\Component\Console\Application->run() at /Users/Tamas/Sites/gbm/app/console:27

**Comment by phiamo** [comment]
can you give me the output of a which composer and which composer.phar for your system?

**Comment by Xigi** [comment]
$ which composer
/usr/local/bin/composer
$ which composer.phar
$

**Comment by danaki** [comment]
Got the same issue:

```
[ yuri@zerg ] /www/suggestor.dev $> php app/console -v mopa:bootstrap:symlink:less



  [PharException]
  internal corruption of phar "/usr/local/Cellar/composer/1.0.0-alpha9/libexec/composer" (__HALT_COMPILER(); not found)



Exception trace:
 () at /www/suggestor.dev/vendor/mopa/composer-bridge/src/Mopa/Bridge/Composer/Adapter/ComposerAdapter.php:77
 Phar::loadPhar() at /www/suggestor.dev/vendor/mopa/composer-bridge/src/Mopa/Bridge/Composer/Adapter/ComposerAdapter.php:77
 Mopa\Bridge\Composer\Adapter\ComposerAdapter::checkComposer() at /www/suggestor.dev/vendor/mopa/composer-bridge/src/Mopa/Bridge/Composer/Adapter/ComposerAdapter.php:105
 Mopa\Bridge\Composer\Adapter\ComposerAdapter::getComposer() at /www/suggestor.dev/vendor/mopa/bootstrap-bundle/Mopa/Bundle/BootstrapBundle/Command/BaseBootstrapSymlinkCommand.php:43
 Mopa\Bundle\BootstrapBundle\Command\BaseBootstrapSymlinkCommand->execute() at /www/suggestor.dev/vendor/symfony/symfony/src/Symfony/Component/Console/Command/Command.php:253
 Symfony\Component\Console\Command\Command->run() at /www/suggestor.dev/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:882
 Symfony\Component\Console\Application->doRunCommand() at /www/suggestor.dev/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:195
 Symfony\Component\Console\Application->doRun() at /www/suggestor.dev/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Console/Application.php:96
 Symfony\Bundle\FrameworkBundle\Console\Application->doRun() at /www/suggestor.dev/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:126
 Symfony\Component\Console\Application->run() at /www/suggestor.dev/app/console:27


mopa:bootstrap:symlink:less [-f|--force] [-m|--manual] [--no-symlink] [pathToTwitterBootstrap] [pathToMopaBootstrapBundle]

[ yuri@zerg ] /www/suggestor.dev $> which composer
/usr/local/bin/composer
```

**Comment by phiamo** [comment]
could you do a ls -la /usr/local/bin/composer
and which php version are you using, even that i dont believe you are lover than 5.1.0 where the function was introduced

**Comment by Xigi** [comment]
$ ls -la /usr/local/bin/composer
lrwxr-xr-x  1 Tamas  admin  44 Dec 16 12:52 /usr/local/bin/composer -> ../Cellar/composer/1.0.0-alpha9/bin/composer

$ php -v
PHP 5.5.19 (cli) (built: Dec 14 2014 14:06:19) 
Copyright (c) 1997-2014 The PHP Group
Zend Engine v2.5.0, Copyright (c) 1998-2014 Zend Technologies

**Comment by phiamo** [comment]
could you try creating a symlink in your local project to your global composer and try again, i know its not a clean solution, but if it works :/ ....

**Comment by Xigi** [comment]
Nope, same error. Tried with both composer and composer.phar filename

**Comment by phiamo** [comment]
can you try a composer self-update
composer --version and try again with -vvv ?

**Comment by danaki** [comment]
Works for me if I download composer.phar to project dir.

**Comment by phiamo** [comment]
at least a workaround ... since i dont have a mac i cant test homebrew software ...

**Comment by phiamo** [comment]
added info to the README.md file, so a workaround is available. This issue is not really resolved, but until we have a better solution available it doesnt need to be open

**Comment by Xigi** [comment]
Thank you
