### ISSUE TITLE
Symfony 2.4 + update

### ISSUE THREAD

**Issue by Nickolaus** [phiamo/MopaComposerBridge#13]
replace call "registerNamespaces" with "addPrefixes", or use the deprecated UniversalClassLoader instead

**Comment by phiamo** [comment]
@Nickolaus is there a error displayed on on your System, or is this just a comment for future Versions ?

**Comment by Nickolaus** [comment]
look at the symfony classes "registerNamespaces" is deprecated since 2.4 I think, therefore symfony versions above 2.4 need to use addPrefixes<br/>So, yes it is an error everyone who uses a symfony version including the change will get a method undefined error

**Comment by phiamo** [comment]
so we need to fix this ...

**Comment by Nickolaus** [comment]
yes... sorry didn't want to close this.... must have hit the wrong button

**Comment by sabliao** [comment]
Will there be a pull request soon? I'm using this w/ Symfony v2.6, and I get the error described above. Here's the output when I try to do composer update:
````
Fatal error: Call to undefined method 
Symfony\Component\ClassLoader\ClassLoader::registerNamespaces() in .../vendor/mopa/composer-
bridge/src/Mopa/Bridge/Composer/Adapter/ComposerAdapter.php on line 84
````

**Comment by Nickolaus** [comment]
if you need the install command now, just exchange "registerNamespaces" with "addPrefixes" in ComposerAdapter class, then you can run the command properly, ... note: you will lose the local changes with every composer update

**Comment by phiamo** [comment]
@Nickolaus could you create a PR regarding this?

**Comment by phiamo** [comment]
merged! thanks a lot!
